@extends('layouts.main')

@section('content')
    <section id="privacy-policy" class="text-color-100">
        <div class="row justify-content-center mb-4">
            <div class="col-12 col-sm-9">
                <h2 class="fw-bold text-center mb-15">Privacy & Policy</h1>
                    <p class="fw-medium text-center mb-10">Effective Date: January 01, 2024</p>
                    <p class="fw-medium text-center mb-0">Last updated: January 02, 2024</p>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-12 col-sm-9">
                <h3 class="fw-semibold">1. Introduction</h3>
                <p class="">Welcome to Kpop Soulmate Web Apps. We are committed to protecting your privacy and
                    ensuring the security of your personal information. This Privacy Policy outlines how we collect, use,
                    disclose, and safeguard your information when you use our website and services. If you have additional
                    questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>
                <h3 class="fw-semibold">2. Definition</h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul>
                    <li>
                        <p><strong>Account:</strong> means a unique account created for You to access our Service or parts
                            of
                            our Service.</p>
                    </li>
                    <li>
                        <p><strong>Affiliate:</strong> means an entity that controls, is controlled by or is under common
                            control with a party, where &quot;control&quot; means ownership of 50% or more of the shares,
                            equity interest or other securities entitled to vote for election of directors or other managing
                            authority.</p>
                    </li>
                    <li>
                        <p><strong>Company:</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;,
                            &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Kpop Soulmate.</p>
                    </li>
                    <li>
                        <p><strong>Cookies:</strong> are small files that are placed on Your computer, mobile device or any
                            other device by a website, containing the details of Your browsing history on that website among
                            its many uses.</p>
                    </li>
                    <li>
                        <p><strong>Country:</strong> refers to: Indonesia</p>
                    </li>
                    <li>
                        <p><strong>Device:</strong> means any device that can access the Service such as a computer, a
                            cellphone or a digital tablet.</p>
                    </li>
                    <li>
                        <p><strong>Personal Data:</strong> is any information that relates to an identified or identifiable
                            individual.</p>
                    </li>
                    <li>
                        <p><strong>Service:</strong> refers to the Website.</p>
                    </li>
                    <li>
                        <p><strong>Service Provider:</strong> means any natural or legal person who processes the data on
                            behalf of the Company. It refers to third-party companies or individuals employed by the Company
                            to facilitate the Service, to provide the Service on behalf of the Company, to perform services
                            related to the Service or to assist the Company in analyzing how the Service is used.</p>
                    </li>
                    <li>
                        <p><strong>Third-party Social Media Service:</strong> refers to any website or any social network
                            website through which a User can log in or create an account to use the Service.</p>
                    </li>
                    <li>
                        <p><strong>Usage Data:</strong> refers to data collected automatically, either generated by the use
                            of the Service or from the Service infrastructure itself (for example, the duration of a page
                            visit).</p>
                    </li>
                    <li>
                        <p><strong>Website:</strong> refers to Kpop Soulmate Web Apps, accessible from <a
                                href="https://www.kpopsoulmate.site" rel="external nofollow noopener"
                                class="text-decoration-none text-color-secondary"
                                target="_blank">https://www.kpopsoulmate.site</a></p>
                    </li>
                    <li>
                        <p><strong>You:</strong> means the individual accessing or using the Service, or the company, or
                            other legal entity on behalf of which such individual is accessing or using the Service, as
                            applicable.</p>
                    </li>
                </ul>
                <h3 class="fw-semibold">3. Information We Collect</h3>
                <p>We may collect the following types of information:</p>
                <h4 class="fw-semibold">3.1. Personal Data</h4>
                <ul>
                    <li><strong>Name</strong> (We recommend you use your YouTube Channel Name Instead of your own name)</li>
                    <li><strong>Email</strong></li>
                    <li><strong>Username</strong></li>
                    <li><strong>Profile Picture</strong> (We recommend using the same avatar that matches your YouTube
                        Channel)</li>
                    <li><strong>Other Identifying Information</strong></li>
                </ul>
                <h4 class="fw-semibold">3.2. Usage Data</h4>
                <p>When you use the Service, Usage Data is automatically gathered. We may collect information about your
                    activities with our website and services, such as your IP address, browser type, pages viewed, and
                    interactions with our website.</p>
                <h4 class="fw-semibold">3.3. Information from Third-Party Social Media Service (Google)</h4>
                <p>We enable You to establish an account and log in to the Service using Your Google account. If You choose
                    to register for or otherwise provide us access to a Google Service, We may collect Personal data that is
                    already linked with Your Google account, such as Your name, email address, activity, or contact list.
                </p>
                <p>If You give such information and Personal Data, whether at registration or elsewhere, You grant the
                    Company permission to use, disclose, and retain it in accordance with this Privacy Policy.</p>
                <h4 class="fw-semibold">3.4. Cookies and Tracking Technologies</h4>
                <ul>
                    <li><strong>Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your
                        browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not
                        accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your
                        browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                    <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small
                        electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel
                        gifs) that permit the Company, for example, to count users who have visited those pages or opened an
                        email and for other related website statistics (for example, recording the popularity of a certain
                        section and verifying system and server integrity)</li>
                </ul>
                <p>We may use cookies and similar tracking technologies to collect information about your browsing behavior.
                    Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or
                    mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web
                    browser. You can learn more about cookies on TermsFeed website article.</p>
                <p>Both session and persistent cookies are used by us. These Cookies are necessary in order to give You
                    access to services on the Website and to use certain of its features. They aid in user authentication
                    and guard against unauthorized usage of user accounts. The services You have requested cannot be
                    delivered without these Cookies, and We only use these Cookies in order to fulfill Your request.</p>
                <h3 class="fw-semibold">4. How We Use Your Information</h3>
                <p class="mb-10">We use the information we collect for various purposes, including:</p>
                <ul>
                    <li>Providing and maintaining our services.</li>
                    <li>To manage Your Account and your requests</li>
                    <li>Communicating with you.</li>
                    <li>Analyzing usage and improving our website.</li>
                    <li>For other purposes, such as data analysis, identifying usage trends, determining the effectiveness
                        of our promotional campaigns and to evaluate and improve our Service, products, services, marketing
                        and your experience</li>
                    <li>Protecting our legal rights and interests.</li>
                </ul>
                <h3 class="fw-semibold">5. Disclosure of Your Information</h3>
                <p class="mb-10">We may share your information with:</p>
                <ul>
                    <li><strong class="fw-semibold">Service providers:</strong> who assist us in running our website and
                        services.</li>
                    <li><strong class="fw-semibold">Legal authorities:</strong> when required by law or to protect our
                        interests.</li>
                    <li><strong class="fw-semibold">Third parties:</strong> in connection with a business transaction, such
                        as a merger or acquisition.</li>
                    <li><strong class="fw-semibold">Business Transactions:</strong> If the Company is involved in a merger,
                        acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your
                        Personal Data is transferred and becomes subject to a different Privacy Policy.</li>
                    <li><strong class="fw-semibold">Law enforcement:</strong> Under certain circumstances, the Company may
                        be required to disclose Your Personal Data if required to do so by law or in response to valid
                        requests by public authorities (e.g. a court or a government agency).</li>
                    <li><strong class="fw-semibold">Other legal requirements:</strong> We may disclose Your Personal Data in
                        the good faith belief that such action is necessary to:
                        <ol>
                            <li>Comply with a legal obligation</li>
                            <li>Protect and defend the rights or property of the Company</li>
                            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                            <li>Protect the personal safety of Users of the Service or the public</li>
                            <li>Protect against legal liability</li>
                        </ol>
                    </li>
                </ul>
                <h3 class="fw-semibold">6. User Rights</h3>
                <p>You have the right to access and update your personal information, opt out of receiving marketing
                    communications, and delete your account and personal data.</p>
                <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have
                    one, and visiting the account settings section that allows you to manage Your personal information. You
                    may also contact Us to request access to, correct, or delete any personal information that You have
                    provided to Us.</p>

                <h3 class="fw-semibold">7. Security</h3>
                <p>We take reasonable measures to protect your information from unauthorized access, disclosure, alteration,
                    or destruction. But remember that no method of transmission over the Internet, or method of electronic
                    storage is 100% secure</p>

                <h3 class="fw-semibold">8. Children's Privacy</h3>
                <p>Another part of our priority is adding protection for children while using the internet. Our services are
                    not intended for children under the age of 13, and we do not knowingly collect personal information from
                    children. We encourage parents and guardians to observe, participate in, and/or monitor and guide their
                    online activity.</p>
                <p>If you think that your child provided this kind of information on our website, we strongly encourage you
                    to contact us immediately and we will do our best efforts to promptly remove such information from our
                    records.</p>

                <h3 class="fw-semibold">9. Contact Us</h3>
                <p class="mb-4">If you have any questions about this Privacy Policy, You can contact us via email <a
                        href="mailto:bgkfuntastic@gmail.com"
                        class="text-color-secondary text-decoration-none">bgkfuntastic@gmail.com</a>
                </p>

                <p class="mb-0 text-center">This Privacy Policy has been
                    created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/"
                        target="_blank" class="text-decoration-none text-color-secondary"> Privacy Policy Generator </a> and
                    <a href="https://www.privacypolicyonline.com/" target="_blank"
                        class="text-decoration-none text-color-secondary">Privacy Policy Online</a>.
                </p>
            </div>
        </div>
    </section>
@endsection
